CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "role" varchar,
  "created_at" timestamp
);

CREATE TABLE "campaigns" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "name" varchar,
  "start_date" date,
  "end_date" date,
  "budget" decimal(10,2),
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "campaign_id" integer DEFAULT null,
  "title" varchar,
  "body" text,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "competitors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "instagram" varchar,
  "facebook" varchar,
  "tiktok" varchar,
  "twitter" varchar,
  "youtube" varchar,
  "website" varchar,
  "created_at" timestamp
);

COMMENT ON COLUMN "campaigns"."user_id" IS 'Campaign owner or manager';

COMMENT ON COLUMN "campaigns"."budget" IS 'Optional field to track campaign budget';

COMMENT ON COLUMN "posts"."user_id" IS 'Author of the post';

COMMENT ON COLUMN "posts"."campaign_id" IS 'Which campaign this post belongs to (if any)';

COMMENT ON COLUMN "posts"."body" IS 'Content of the post';

COMMENT ON COLUMN "competitors"."website" IS 'Optional field if you want to store competitor website';

ALTER TABLE "campaigns" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");
