// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: competitor_posts.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const searchCompetitorPosts = `-- name: SearchCompetitorPosts :many
SELECT
  cp.id,
  cp.competitor_id,
  cp.platform,
  cp.post_id,
  cp.content,
  cp.posted_at,
  cp.engagement,
  c.username as competitor_username
FROM competitor_posts cp
JOIN competitors c ON c.id = cp.competitor_id
JOIN user_competitors uc ON uc.competitor_id = c.id
WHERE uc.user_id = $1
  AND (uc.group_id = $2 OR uc.group_id IS NULL)
  AND (
    to_tsvector('english', COALESCE(cp.content, '')) @@ websearch_to_tsquery('english', $3)
    OR cp.content ILIKE '%' || $3 || '%'
  )
ORDER BY cp.posted_at DESC
LIMIT $4
`

type SearchCompetitorPostsParams struct {
	UserID             int32         `json:"user_id"`
	GroupID            sql.NullInt32 `json:"group_id"`
	WebsearchToTsquery string        `json:"websearch_to_tsquery"`
	Limit              int32         `json:"limit"`
}

type SearchCompetitorPostsRow struct {
	ID                 int32                 `json:"id"`
	CompetitorID       uuid.NullUUID         `json:"competitor_id"`
	Platform           string                `json:"platform"`
	PostID             string                `json:"post_id"`
	Content            sql.NullString        `json:"content"`
	PostedAt           sql.NullTime          `json:"posted_at"`
	Engagement         pqtype.NullRawMessage `json:"engagement"`
	CompetitorUsername string                `json:"competitor_username"`
}

func (q *Queries) SearchCompetitorPosts(ctx context.Context, arg SearchCompetitorPostsParams) ([]SearchCompetitorPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCompetitorPosts,
		arg.UserID,
		arg.GroupID,
		arg.WebsearchToTsquery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCompetitorPostsRow
	for rows.Next() {
		var i SearchCompetitorPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitorID,
			&i.Platform,
			&i.PostID,
			&i.Content,
			&i.PostedAt,
			&i.Engagement,
			&i.CompetitorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
