// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: competitor_posts.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getCompetitorAnalytics = `-- name: GetCompetitorAnalytics :many
SELECT
  c.id,
  c.platform,
  c.username,
  c.followers,
  c.engagement_rate,
  c.growth_rate,
  c.posting_frequency
FROM competitors c
JOIN user_competitors uc ON uc.competitor_id = c.id
WHERE uc.user_id = $1
  AND (uc.group_id = $2 OR uc.group_id IS NULL)
`

type GetCompetitorAnalyticsParams struct {
	UserID  int32         `json:"user_id"`
	GroupID sql.NullInt32 `json:"group_id"`
}

type GetCompetitorAnalyticsRow struct {
	ID               uuid.UUID      `json:"id"`
	Platform         string         `json:"platform"`
	Username         string         `json:"username"`
	Followers        sql.NullInt64  `json:"followers"`
	EngagementRate   sql.NullString `json:"engagement_rate"`
	GrowthRate       sql.NullString `json:"growth_rate"`
	PostingFrequency sql.NullString `json:"posting_frequency"`
}

func (q *Queries) GetCompetitorAnalytics(ctx context.Context, arg GetCompetitorAnalyticsParams) ([]GetCompetitorAnalyticsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompetitorAnalytics, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompetitorAnalyticsRow
	for rows.Next() {
		var i GetCompetitorAnalyticsRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Username,
			&i.Followers,
			&i.EngagementRate,
			&i.GrowthRate,
			&i.PostingFrequency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentCompetitorPosts = `-- name: GetRecentCompetitorPosts :many
SELECT
  cp.id,
  cp.competitor_id,
  cp.platform,
  cp.post_id,
  cp.content,
  cp.posted_at,
  cp.engagement,
  c.username as competitor_username
FROM competitor_posts cp
JOIN competitors c ON c.id = cp.competitor_id
JOIN user_competitors uc ON uc.competitor_id = c.id
WHERE uc.user_id = $1
  AND (uc.group_id = $2 OR uc.group_id IS NULL)
ORDER BY cp.posted_at DESC
LIMIT $3
`

type GetRecentCompetitorPostsParams struct {
	UserID  int32         `json:"user_id"`
	GroupID sql.NullInt32 `json:"group_id"`
	Limit   int32         `json:"limit"`
}

type GetRecentCompetitorPostsRow struct {
	ID                 int32                 `json:"id"`
	CompetitorID       uuid.NullUUID         `json:"competitor_id"`
	Platform           string                `json:"platform"`
	PostID             string                `json:"post_id"`
	Content            sql.NullString        `json:"content"`
	PostedAt           sql.NullTime          `json:"posted_at"`
	Engagement         pqtype.NullRawMessage `json:"engagement"`
	CompetitorUsername string                `json:"competitor_username"`
}

func (q *Queries) GetRecentCompetitorPosts(ctx context.Context, arg GetRecentCompetitorPostsParams) ([]GetRecentCompetitorPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentCompetitorPosts, arg.UserID, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentCompetitorPostsRow
	for rows.Next() {
		var i GetRecentCompetitorPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitorID,
			&i.Platform,
			&i.PostID,
			&i.Content,
			&i.PostedAt,
			&i.Engagement,
			&i.CompetitorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCompetitorPosts = `-- name: SearchCompetitorPosts :many
SELECT
  cp.id,
  cp.competitor_id,
  cp.platform,
  cp.post_id,
  cp.content,
  cp.posted_at,
  cp.engagement,
  c.username as competitor_username
FROM competitor_posts cp
JOIN competitors c ON c.id = cp.competitor_id
JOIN user_competitors uc ON uc.competitor_id = c.id
WHERE uc.user_id = $1
  AND (uc.group_id = $2 OR uc.group_id IS NULL)
ORDER BY cp.posted_at DESC
LIMIT $3
`

type GetRecentCompetitorPostsParams struct {
	UserID  int32         `json:"user_id"`
	GroupID sql.NullInt32 `json:"group_id"`
	Limit   int32         `json:"limit"`
}

type GetRecentCompetitorPostsRow struct {
	ID                 int32                 `json:"id"`
	CompetitorID       uuid.NullUUID         `json:"competitor_id"`
	Platform           string                `json:"platform"`
	PostID             string                `json:"post_id"`
	Content            sql.NullString        `json:"content"`
	PostedAt           sql.NullTime          `json:"posted_at"`
	Engagement         pqtype.NullRawMessage `json:"engagement"`
	CompetitorUsername string                `json:"competitor_username"`
}

func (q *Queries) GetRecentCompetitorPosts(ctx context.Context, arg GetRecentCompetitorPostsParams) ([]GetRecentCompetitorPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentCompetitorPosts, arg.UserID, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentCompetitorPostsRow
	for rows.Next() {
		var i GetRecentCompetitorPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitorID,
			&i.Platform,
			&i.PostID,
			&i.Content,
			&i.PostedAt,
			&i.Engagement,
			&i.CompetitorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCompetitorPosts = `-- name: SearchCompetitorPosts :many
SELECT
  cp.id,
  cp.competitor_id,
  cp.platform,
  cp.post_id,
  cp.content,
  cp.posted_at,
  cp.engagement,
  c.username as competitor_username,
  -- Calculate relevance score for ranking
  CASE
    WHEN to_tsvector('english', COALESCE(cp.content, '')) @@ websearch_to_tsquery('english', $3) THEN 3
    WHEN cp.content ILIKE '%' || $3 || '%' THEN 2
    ELSE 1
  END as relevance
FROM competitor_posts cp
JOIN competitors c ON c.id = cp.competitor_id
JOIN user_competitors uc ON uc.competitor_id = c.id
WHERE uc.user_id = $1
  AND (uc.group_id = $2 OR uc.group_id IS NULL)
  AND (
    -- Try exact full-text match first (all terms must match)
    to_tsvector('english', COALESCE(cp.content, '')) @@ websearch_to_tsquery('english', $3)
    -- Or partial ILIKE match
    OR cp.content ILIKE '%' || $3 || '%'
    -- Or match ANY of the terms (more flexible)
    OR to_tsvector('english', COALESCE(cp.content, '')) @@ plainto_tsquery('english', $3)
  )
ORDER BY relevance DESC, cp.posted_at DESC
LIMIT $4
`

type SearchCompetitorPostsParams struct {
	UserID             int32         `json:"user_id"`
	GroupID            sql.NullInt32 `json:"group_id"`
	WebsearchToTsquery string        `json:"websearch_to_tsquery"`
	Limit              int32         `json:"limit"`
}

type SearchCompetitorPostsRow struct {
	ID                 int32                 `json:"id"`
	CompetitorID       uuid.NullUUID         `json:"competitor_id"`
	Platform           string                `json:"platform"`
	PostID             string                `json:"post_id"`
	Content            sql.NullString        `json:"content"`
	PostedAt           sql.NullTime          `json:"posted_at"`
	Engagement         pqtype.NullRawMessage `json:"engagement"`
	CompetitorUsername string                `json:"competitor_username"`
	Relevance          int32                 `json:"relevance"`
}

func (q *Queries) SearchCompetitorPosts(ctx context.Context, arg SearchCompetitorPostsParams) ([]SearchCompetitorPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCompetitorPosts,
		arg.UserID,
		arg.GroupID,
		arg.WebsearchToTsquery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCompetitorPostsRow
	for rows.Next() {
		var i SearchCompetitorPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitorID,
			&i.Platform,
			&i.PostID,
			&i.Content,
			&i.PostedAt,
			&i.Engagement,
			&i.CompetitorUsername,
			&i.Relevance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
