// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: competitor_posts.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const getCompetitorAnalytics = `-- name: GetCompetitorAnalytics :many
SELECT
  c.id,
  c.display_name,
  cpr.platform,
  cpr.handle,
  cpr.followers,
  cpr.engagement_rate,
  cpr.growth_rate,
  cpr.posting_frequency
FROM competitors c
JOIN competitor_profiles cpr ON cpr.competitor_id = c.id
JOIN user_competitors uc ON uc.competitor_id = c.id
WHERE uc.user_id = $1
  AND (uc.group_id = $2 OR uc.group_id IS NULL)
`

type GetCompetitorAnalyticsParams struct {
	UserID  int32         `json:"user_id"`
	GroupID sql.NullInt32 `json:"group_id"`
}

type GetCompetitorAnalyticsRow struct {
	ID               uuid.UUID      `json:"id"`
	DisplayName      sql.NullString `json:"display_name"`
	Platform         string         `json:"platform"`
	Handle           string         `json:"handle"`
	Followers        sql.NullInt64  `json:"followers"`
	EngagementRate   sql.NullString `json:"engagement_rate"`
	GrowthRate       sql.NullString `json:"growth_rate"`
	PostingFrequency sql.NullString `json:"posting_frequency"`
}

func (q *Queries) GetCompetitorAnalytics(ctx context.Context, arg GetCompetitorAnalyticsParams) ([]GetCompetitorAnalyticsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompetitorAnalytics, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompetitorAnalyticsRow
	for rows.Next() {
		var i GetCompetitorAnalyticsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Platform,
			&i.Handle,
			&i.Followers,
			&i.EngagementRate,
			&i.GrowthRate,
			&i.PostingFrequency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompetitorProfileByPlatformAndHandle = `-- name: GetCompetitorProfileByPlatformAndHandle :one
SELECT cp.id, cp.competitor_id, cp.platform, cp.handle, cp.profile_url, cp.followers, cp.engagement_rate, cp.growth_rate, cp.posting_frequency, cp.last_checked, c.display_name
FROM competitor_profiles cp
JOIN competitors c ON c.id = cp.competitor_id
WHERE cp.platform = $1 AND cp.handle = $2
`

type GetCompetitorProfileByPlatformAndHandleParams struct {
	Platform string `json:"platform"`
	Handle   string `json:"handle"`
}

type GetCompetitorProfileByPlatformAndHandleRow struct {
	ID               uuid.UUID      `json:"id"`
	CompetitorID     uuid.UUID      `json:"competitor_id"`
	Platform         string         `json:"platform"`
	Handle           string         `json:"handle"`
	ProfileUrl       sql.NullString `json:"profile_url"`
	Followers        sql.NullInt64  `json:"followers"`
	EngagementRate   sql.NullString `json:"engagement_rate"`
	GrowthRate       sql.NullString `json:"growth_rate"`
	PostingFrequency sql.NullString `json:"posting_frequency"`
	LastChecked      sql.NullTime   `json:"last_checked"`
	DisplayName      sql.NullString `json:"display_name"`
}

func (q *Queries) GetCompetitorProfileByPlatformAndHandle(ctx context.Context, arg GetCompetitorProfileByPlatformAndHandleParams) (GetCompetitorProfileByPlatformAndHandleRow, error) {
	row := q.db.QueryRowContext(ctx, getCompetitorProfileByPlatformAndHandle, arg.Platform, arg.Handle)
	var i GetCompetitorProfileByPlatformAndHandleRow
	err := row.Scan(
		&i.ID,
		&i.CompetitorID,
		&i.Platform,
		&i.Handle,
		&i.ProfileUrl,
		&i.Followers,
		&i.EngagementRate,
		&i.GrowthRate,
		&i.PostingFrequency,
		&i.LastChecked,
		&i.DisplayName,
	)
	return i, err
}

const getRecentCompetitorPosts = `-- name: GetRecentCompetitorPosts :many
SELECT
  cp.id,
  cp.competitor_id,
  cp.platform,
  cp.post_id,
  cp.content,
  cp.posted_at,
  cp.engagement,
  c.display_name as competitor_name,
  cpr.handle as competitor_handle
FROM competitor_posts cp
JOIN competitors c ON c.id = cp.competitor_id
JOIN competitor_profiles cpr ON cpr.id = cp.profile_id
JOIN user_competitors uc ON uc.competitor_id = c.id
WHERE uc.user_id = $1
  AND (uc.group_id = $2 OR uc.group_id IS NULL)
ORDER BY cp.posted_at DESC
LIMIT $3
`

type GetRecentCompetitorPostsParams struct {
	UserID  int32         `json:"user_id"`
	GroupID sql.NullInt32 `json:"group_id"`
	Limit   int32         `json:"limit"`
}

type GetRecentCompetitorPostsRow struct {
	ID               int32                 `json:"id"`
	CompetitorID     uuid.NullUUID         `json:"competitor_id"`
	Platform         string                `json:"platform"`
	PostID           string                `json:"post_id"`
	Content          sql.NullString        `json:"content"`
	PostedAt         sql.NullTime          `json:"posted_at"`
	Engagement       pqtype.NullRawMessage `json:"engagement"`
	CompetitorName   sql.NullString        `json:"competitor_name"`
	CompetitorHandle string                `json:"competitor_handle"`
}

func (q *Queries) GetRecentCompetitorPosts(ctx context.Context, arg GetRecentCompetitorPostsParams) ([]GetRecentCompetitorPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentCompetitorPosts, arg.UserID, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentCompetitorPostsRow
	for rows.Next() {
		var i GetRecentCompetitorPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitorID,
			&i.Platform,
			&i.PostID,
			&i.Content,
			&i.PostedAt,
			&i.Engagement,
			&i.CompetitorName,
			&i.CompetitorHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCompetitorPosts = `-- name: SearchCompetitorPosts :many
SELECT
  cp.id,
  cp.competitor_id,
  cp.platform,
  cp.post_id,
  cp.content,
  cp.posted_at,
  cp.engagement,
  c.display_name as competitor_name,
  cpr.handle as competitor_handle,
  -- Calculate relevance score for ranking
  CASE
    WHEN to_tsvector('english', COALESCE(cp.content, '')) @@ websearch_to_tsquery('english', $3) THEN 3
    WHEN cp.content ILIKE '%' || $3 || '%' THEN 2
    ELSE 1
  END as relevance
FROM competitor_posts cp
JOIN competitors c ON c.id = cp.competitor_id
JOIN competitor_profiles cpr ON cpr.id = cp.profile_id
JOIN user_competitors uc ON uc.competitor_id = c.id
WHERE uc.user_id = $1
  AND (uc.group_id = $2 OR uc.group_id IS NULL)
  AND (
    -- Try exact full-text match first (all terms must match)
    to_tsvector('english', COALESCE(cp.content, '')) @@ websearch_to_tsquery('english', $3)
    -- Or partial ILIKE match
    OR cp.content ILIKE '%' || $3 || '%'
    -- Or match ANY of the terms (more flexible)
    OR to_tsvector('english', COALESCE(cp.content, '')) @@ plainto_tsquery('english', $3)
  )
ORDER BY relevance DESC, cp.posted_at DESC
LIMIT $4
`

type SearchCompetitorPostsParams struct {
	UserID             int32         `json:"user_id"`
	GroupID            sql.NullInt32 `json:"group_id"`
	WebsearchToTsquery string        `json:"websearch_to_tsquery"`
	Limit              int32         `json:"limit"`
}

type SearchCompetitorPostsRow struct {
	ID               int32                 `json:"id"`
	CompetitorID     uuid.NullUUID         `json:"competitor_id"`
	Platform         string                `json:"platform"`
	PostID           string                `json:"post_id"`
	Content          sql.NullString        `json:"content"`
	PostedAt         sql.NullTime          `json:"posted_at"`
	Engagement       pqtype.NullRawMessage `json:"engagement"`
	CompetitorName   sql.NullString        `json:"competitor_name"`
	CompetitorHandle string                `json:"competitor_handle"`
	Relevance        int32                 `json:"relevance"`
}

func (q *Queries) SearchCompetitorPosts(ctx context.Context, arg SearchCompetitorPostsParams) ([]SearchCompetitorPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCompetitorPosts,
		arg.UserID,
		arg.GroupID,
		arg.WebsearchToTsquery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCompetitorPostsRow
	for rows.Next() {
		var i SearchCompetitorPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitorID,
			&i.Platform,
			&i.PostID,
			&i.Content,
			&i.PostedAt,
			&i.Engagement,
			&i.CompetitorName,
			&i.CompetitorHandle,
			&i.Relevance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompetitorPost = `-- name: UpsertCompetitorPost :one
INSERT INTO competitor_posts (
  competitor_id,
  platform,
  post_id,
  content,
  media,
  posted_at,
  engagement,
  hashtags,
  scraped_at
)
VALUES (
  $1, -- competitor_id (UUID)
  $2, -- platform (VARCHAR)
  $3, -- post_id (VARCHAR)
  $4, -- content (TEXT)
  $5::jsonb, -- media (JSONB)
  $6, -- posted_at (TIMESTAMP)
  $7::jsonb, -- engagement (JSONB)
  $8, -- hashtags (TEXT[])
  $9  -- scraped_at (TIMESTAMP)
)
ON CONFLICT (platform, post_id) DO UPDATE SET
  content = EXCLUDED.content,
  media = EXCLUDED.media,
  posted_at = EXCLUDED.posted_at,
  engagement = EXCLUDED.engagement,
  hashtags = EXCLUDED.hashtags,
  scraped_at = EXCLUDED.scraped_at
RETURNING id, competitor_id, username, platform, post_id, content, media, posted_at, engagement, hashtags, scraped_at, caption_hash, profile_id
`

type UpsertCompetitorPostParams struct {
	CompetitorID uuid.NullUUID   `json:"competitor_id"`
	Platform     string          `json:"platform"`
	PostID       string          `json:"post_id"`
	Content      sql.NullString  `json:"content"`
	Column5      json.RawMessage `json:"column_5"`
	PostedAt     sql.NullTime    `json:"posted_at"`
	Column7      json.RawMessage `json:"column_7"`
	Hashtags     []string        `json:"hashtags"`
	ScrapedAt    sql.NullTime    `json:"scraped_at"`
}

func (q *Queries) UpsertCompetitorPost(ctx context.Context, arg UpsertCompetitorPostParams) (CompetitorPost, error) {
	row := q.db.QueryRowContext(ctx, upsertCompetitorPost,
		arg.CompetitorID,
		arg.Platform,
		arg.PostID,
		arg.Content,
		arg.Column5,
		arg.PostedAt,
		arg.Column7,
		pq.Array(arg.Hashtags),
		arg.ScrapedAt,
	)
	var i CompetitorPost
	err := row.Scan(
		&i.ID,
		&i.CompetitorID,
		&i.Username,
		&i.Platform,
		&i.PostID,
		&i.Content,
		&i.Media,
		&i.PostedAt,
		&i.Engagement,
		pq.Array(&i.Hashtags),
		&i.ScrapedAt,
		&i.CaptionHash,
		&i.ProfileID,
	)
	return i, err
}

const upsertCompetitorProfile = `-- name: UpsertCompetitorProfile :one
INSERT INTO competitor_profiles (competitor_id, platform, handle, profile_url, last_checked)
VALUES ($1, $2, $3, $4, NULL)
ON CONFLICT (competitor_id, platform) DO UPDATE SET
  handle = EXCLUDED.handle,
  profile_url = EXCLUDED.profile_url,
  last_checked = EXCLUDED.last_checked
RETURNING id, competitor_id, platform, handle, profile_url, followers, engagement_rate, growth_rate, posting_frequency, last_checked
`

type UpsertCompetitorProfileParams struct {
	CompetitorID uuid.UUID      `json:"competitor_id"`
	Platform     string         `json:"platform"`
	Handle       string         `json:"handle"`
	ProfileUrl   sql.NullString `json:"profile_url"`
}

func (q *Queries) UpsertCompetitorProfile(ctx context.Context, arg UpsertCompetitorProfileParams) (CompetitorProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertCompetitorProfile,
		arg.CompetitorID,
		arg.Platform,
		arg.Handle,
		arg.ProfileUrl,
	)
	var i CompetitorProfile
	err := row.Scan(
		&i.ID,
		&i.CompetitorID,
		&i.Platform,
		&i.Handle,
		&i.ProfileUrl,
		&i.Followers,
		&i.EngagementRate,
		&i.GrowthRate,
		&i.PostingFrequency,
		&i.LastChecked,
	)
	return i, err
}
