// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competitor_profiles.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCompetitorEntity = `-- name: CreateCompetitorEntity :one
INSERT INTO competitors (display_name)
VALUES ($1)
RETURNING id, last_checked, total_posts, display_name
`

func (q *Queries) CreateCompetitorEntity(ctx context.Context, displayName sql.NullString) (Competitor, error) {
	row := q.db.QueryRowContext(ctx, createCompetitorEntity, displayName)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.LastChecked,
		&i.TotalPosts,
		&i.DisplayName,
	)
	return i, err
}

const createCompetitorProfile = `-- name: CreateCompetitorProfile :one

INSERT INTO competitor_profiles (competitor_id, platform, handle, profile_url)
VALUES ($1, $2, $3, $4)
RETURNING id, competitor_id, platform, handle, profile_url, followers, engagement_rate, growth_rate, posting_frequency, last_checked
`

type CreateCompetitorProfileParams struct {
	CompetitorID uuid.UUID      `json:"competitor_id"`
	Platform     string         `json:"platform"`
	Handle       string         `json:"handle"`
	ProfileUrl   sql.NullString `json:"profile_url"`
}

// Competitor Profiles SQLC Queries
func (q *Queries) CreateCompetitorProfile(ctx context.Context, arg CreateCompetitorProfileParams) (CompetitorProfile, error) {
	row := q.db.QueryRowContext(ctx, createCompetitorProfile,
		arg.CompetitorID,
		arg.Platform,
		arg.Handle,
		arg.ProfileUrl,
	)
	var i CompetitorProfile
	err := row.Scan(
		&i.ID,
		&i.CompetitorID,
		&i.Platform,
		&i.Handle,
		&i.ProfileUrl,
		&i.Followers,
		&i.EngagementRate,
		&i.GrowthRate,
		&i.PostingFrequency,
		&i.LastChecked,
	)
	return i, err
}

const deleteCompetitor = `-- name: DeleteCompetitor :exec
DELETE FROM competitors
WHERE id = $1
`

func (q *Queries) DeleteCompetitor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCompetitor, id)
	return err
}

const deleteCompetitorProfile = `-- name: DeleteCompetitorProfile :exec
DELETE FROM competitor_profiles
WHERE id = $1
`

func (q *Queries) DeleteCompetitorProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCompetitorProfile, id)
	return err
}

const getCompetitorProfileByID = `-- name: GetCompetitorProfileByID :one
SELECT id, competitor_id, platform, handle, profile_url, followers, engagement_rate, growth_rate, posting_frequency, last_checked FROM competitor_profiles
WHERE id = $1
`

func (q *Queries) GetCompetitorProfileByID(ctx context.Context, id uuid.UUID) (CompetitorProfile, error) {
	row := q.db.QueryRowContext(ctx, getCompetitorProfileByID, id)
	var i CompetitorProfile
	err := row.Scan(
		&i.ID,
		&i.CompetitorID,
		&i.Platform,
		&i.Handle,
		&i.ProfileUrl,
		&i.Followers,
		&i.EngagementRate,
		&i.GrowthRate,
		&i.PostingFrequency,
		&i.LastChecked,
	)
	return i, err
}

const getCompetitorWithAllProfiles = `-- name: GetCompetitorWithAllProfiles :one
SELECT c.id, c.last_checked, c.total_posts, c.display_name
FROM competitors c
WHERE c.id = $1
`

func (q *Queries) GetCompetitorWithAllProfiles(ctx context.Context, id uuid.UUID) (Competitor, error) {
	row := q.db.QueryRowContext(ctx, getCompetitorWithAllProfiles, id)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.LastChecked,
		&i.TotalPosts,
		&i.DisplayName,
	)
	return i, err
}

const getProfileByCompetitorAndPlatform = `-- name: GetProfileByCompetitorAndPlatform :one
SELECT id, competitor_id, platform, handle, profile_url, followers, engagement_rate, growth_rate, posting_frequency, last_checked FROM competitor_profiles
WHERE competitor_id = $1 AND platform = $2
`

type GetProfileByCompetitorAndPlatformParams struct {
	CompetitorID uuid.UUID `json:"competitor_id"`
	Platform     string    `json:"platform"`
}

func (q *Queries) GetProfileByCompetitorAndPlatform(ctx context.Context, arg GetProfileByCompetitorAndPlatformParams) (CompetitorProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByCompetitorAndPlatform, arg.CompetitorID, arg.Platform)
	var i CompetitorProfile
	err := row.Scan(
		&i.ID,
		&i.CompetitorID,
		&i.Platform,
		&i.Handle,
		&i.ProfileUrl,
		&i.Followers,
		&i.EngagementRate,
		&i.GrowthRate,
		&i.PostingFrequency,
		&i.LastChecked,
	)
	return i, err
}

const getProfileStats = `-- name: GetProfileStats :many
SELECT 
  cp.id,
  cp.platform,
  cp.handle,
  cp.profile_url,
  cp.followers,
  cp.engagement_rate,
  cp.growth_rate,
  cp.posting_frequency,
  cp.last_checked
FROM competitor_profiles cp
WHERE cp.competitor_id = $1
ORDER BY cp.platform
`

type GetProfileStatsRow struct {
	ID               uuid.UUID      `json:"id"`
	Platform         string         `json:"platform"`
	Handle           string         `json:"handle"`
	ProfileUrl       sql.NullString `json:"profile_url"`
	Followers        sql.NullInt64  `json:"followers"`
	EngagementRate   sql.NullString `json:"engagement_rate"`
	GrowthRate       sql.NullString `json:"growth_rate"`
	PostingFrequency sql.NullString `json:"posting_frequency"`
	LastChecked      sql.NullTime   `json:"last_checked"`
}

func (q *Queries) GetProfileStats(ctx context.Context, competitorID uuid.UUID) ([]GetProfileStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProfileStats, competitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfileStatsRow
	for rows.Next() {
		var i GetProfileStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Handle,
			&i.ProfileUrl,
			&i.Followers,
			&i.EngagementRate,
			&i.GrowthRate,
			&i.PostingFrequency,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetitorsWithProfiles = `-- name: ListCompetitorsWithProfiles :many
SELECT 
  c.id,
  c.display_name,
  c.last_checked,
  c.total_posts
FROM competitors c
JOIN user_competitors uc ON uc.competitor_id = c.id
WHERE uc.user_id = $1 
  AND (
    uc.group_id = $2 
    OR uc.group_id IS NULL
    OR $2 IS NULL
  )
ORDER BY c.display_name
`

type ListCompetitorsWithProfilesParams struct {
	UserID  int32         `json:"user_id"`
	GroupID sql.NullInt32 `json:"group_id"`
}

type ListCompetitorsWithProfilesRow struct {
	ID          uuid.UUID      `json:"id"`
	DisplayName sql.NullString `json:"display_name"`
	LastChecked sql.NullTime   `json:"last_checked"`
	TotalPosts  sql.NullInt64  `json:"total_posts"`
}

func (q *Queries) ListCompetitorsWithProfiles(ctx context.Context, arg ListCompetitorsWithProfilesParams) ([]ListCompetitorsWithProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompetitorsWithProfiles, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitorsWithProfilesRow
	for rows.Next() {
		var i ListCompetitorsWithProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.LastChecked,
			&i.TotalPosts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByCompetitor = `-- name: ListProfilesByCompetitor :many
SELECT id, competitor_id, platform, handle, profile_url, followers, engagement_rate, growth_rate, posting_frequency, last_checked FROM competitor_profiles
WHERE competitor_id = $1
ORDER BY platform
`

func (q *Queries) ListProfilesByCompetitor(ctx context.Context, competitorID uuid.UUID) ([]CompetitorProfile, error) {
	rows, err := q.db.QueryContext(ctx, listProfilesByCompetitor, competitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompetitorProfile
	for rows.Next() {
		var i CompetitorProfile
		if err := rows.Scan(
			&i.ID,
			&i.CompetitorID,
			&i.Platform,
			&i.Handle,
			&i.ProfileUrl,
			&i.Followers,
			&i.EngagementRate,
			&i.GrowthRate,
			&i.PostingFrequency,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompetitorDisplayName = `-- name: UpdateCompetitorDisplayName :one
UPDATE competitors
SET display_name = $2
WHERE id = $1
RETURNING id, last_checked, total_posts, display_name
`

type UpdateCompetitorDisplayNameParams struct {
	ID          uuid.UUID      `json:"id"`
	DisplayName sql.NullString `json:"display_name"`
}

func (q *Queries) UpdateCompetitorDisplayName(ctx context.Context, arg UpdateCompetitorDisplayNameParams) (Competitor, error) {
	row := q.db.QueryRowContext(ctx, updateCompetitorDisplayName, arg.ID, arg.DisplayName)
	var i Competitor
	err := row.Scan(
		&i.ID,
		&i.LastChecked,
		&i.TotalPosts,
		&i.DisplayName,
	)
	return i, err
}

const updateCompetitorProfile = `-- name: UpdateCompetitorProfile :one
UPDATE competitor_profiles
SET handle = $2,
    profile_url = $3,
    followers = $4,
    engagement_rate = $5,
    growth_rate = $6,
    posting_frequency = $7,
    last_checked = $8
WHERE id = $1
RETURNING id, competitor_id, platform, handle, profile_url, followers, engagement_rate, growth_rate, posting_frequency, last_checked
`

type UpdateCompetitorProfileParams struct {
	ID               uuid.UUID      `json:"id"`
	Handle           string         `json:"handle"`
	ProfileUrl       sql.NullString `json:"profile_url"`
	Followers        sql.NullInt64  `json:"followers"`
	EngagementRate   sql.NullString `json:"engagement_rate"`
	GrowthRate       sql.NullString `json:"growth_rate"`
	PostingFrequency sql.NullString `json:"posting_frequency"`
	LastChecked      sql.NullTime   `json:"last_checked"`
}

func (q *Queries) UpdateCompetitorProfile(ctx context.Context, arg UpdateCompetitorProfileParams) (CompetitorProfile, error) {
	row := q.db.QueryRowContext(ctx, updateCompetitorProfile,
		arg.ID,
		arg.Handle,
		arg.ProfileUrl,
		arg.Followers,
		arg.EngagementRate,
		arg.GrowthRate,
		arg.PostingFrequency,
		arg.LastChecked,
	)
	var i CompetitorProfile
	err := row.Scan(
		&i.ID,
		&i.CompetitorID,
		&i.Platform,
		&i.Handle,
		&i.ProfileUrl,
		&i.Followers,
		&i.EngagementRate,
		&i.GrowthRate,
		&i.PostingFrequency,
		&i.LastChecked,
	)
	return i, err
}
