// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Campaign struct {
	ID int32 `json:"id"`
	// Campaign owner or manager
	UserID    sql.NullInt32  `json:"user_id"`
	Name      sql.NullString `json:"name"`
	StartDate sql.NullTime   `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
	// Optional field to track campaign budget
	Budget    sql.NullString `json:"budget"`
	Status    sql.NullString `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Competitor struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	Instagram sql.NullString `json:"instagram"`
	Facebook  sql.NullString `json:"facebook"`
	Tiktok    sql.NullString `json:"tiktok"`
	Twitter   sql.NullString `json:"twitter"`
	Youtube   sql.NullString `json:"youtube"`
	// Optional field if you want to store competitor website
	Website   sql.NullString `json:"website"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Post struct {
	ID int32 `json:"id"`
	// Author of the post
	UserID sql.NullInt32 `json:"user_id"`
	// Which campaign this post belongs to (if any)
	CampaignID sql.NullInt32  `json:"campaign_id"`
	Title      sql.NullString `json:"title"`
	// Content of the post
	Body      sql.NullString `json:"body"`
	Status    sql.NullString `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type User struct {
	ID        int32          `json:"id"`
	Username  sql.NullString `json:"username"`
	Role      sql.NullString `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
