// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Competitor struct {
	ID               uuid.UUID      `json:"id"`
	Platform         string         `json:"platform"`
	Username         string         `json:"username"`
	ProfileUrl       string         `json:"profile_url"`
	LastChecked      sql.NullTime   `json:"last_checked"`
	Followers        sql.NullInt64  `json:"followers"`
	EngagementRate   sql.NullString `json:"engagement_rate"`
	GrowthRate       sql.NullString `json:"growth_rate"`
	PostingFrequency sql.NullString `json:"posting_frequency"`
}

type CompetitorPost struct {
	ID           int32                 `json:"id"`
	CompetitorID uuid.NullUUID         `json:"competitor_id"`
	Platform     string                `json:"platform"`
	PostID       string                `json:"post_id"`
	Content      sql.NullString        `json:"content"`
	Media        pqtype.NullRawMessage `json:"media"`
	PostedAt     sql.NullTime          `json:"posted_at"`
	Engagement   pqtype.NullRawMessage `json:"engagement"`
	Hashtags     []string              `json:"hashtags"`
	ScrapedAt    sql.NullTime          `json:"scraped_at"`
}

type DailyFollower struct {
	ID            int32     `json:"id"`
	RecordDate    time.Time `json:"record_date"`
	FollowerCount int64     `json:"follower_count"`
}

type Group struct {
	ID          int32          `json:"id"`
	UserID      int32          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type GroupItem struct {
	ID        int32                 `json:"id"`
	GroupID   int32                 `json:"group_id"`
	Platform  string                `json:"platform"`
	Data      pqtype.NullRawMessage `json:"data"`
	CreatedAt sql.NullTime          `json:"created_at"`
	UpdatedAt sql.NullTime          `json:"updated_at"`
}

type Post struct {
	ID              int32        `json:"id"`
	GroupID         int32        `json:"group_id"`
	Title           string       `json:"title"`
	SocialMediaLink string       `json:"social_media_link"`
	CreatedAt       sql.NullTime `json:"created_at"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID    `json:"id"`
	UserID    int32        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
}

type SocialmediaDatum struct {
	ID        int32           `json:"id"`
	GroupID   int32           `json:"group_id"`
	Platform  string          `json:"platform"`
	Type      string          `json:"type"`
	Data      json.RawMessage `json:"data"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type UploadJob struct {
	ID            string         `json:"id"`
	UserID        int32          `json:"user_id"`
	GroupID       sql.NullInt32  `json:"group_id"`
	Platform      string         `json:"platform"`
	VideoPath     string         `json:"video_path"`
	StorageType   string         `json:"storage_type"`
	FileUrl       sql.NullString `json:"file_url"`
	Status        string         `json:"status"`
	Caption       sql.NullString `json:"caption"`
	UserTitle     sql.NullString `json:"user_title"`
	UserHashtags  []string       `json:"user_hashtags"`
	AiTitle       sql.NullString `json:"ai_title"`
	AiHashtags    []string       `json:"ai_hashtags"`
	AiPostTime    sql.NullTime   `json:"ai_post_time"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	ScheduledDate sql.NullTime   `json:"scheduled_date"`
}

type User struct {
	ID            int32          `json:"id"`
	Username      string         `json:"username"`
	Email         string         `json:"email"`
	PasswordHash  string         `json:"password_hash"`
	OauthProvider sql.NullString `json:"oauth_provider"`
	OauthID       sql.NullString `json:"oauth_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type UserCompetitor struct {
	ID           int32         `json:"id"`
	UserID       int32         `json:"user_id"`
	GroupID      sql.NullInt32 `json:"group_id"`
	CompetitorID uuid.UUID     `json:"competitor_id"`
	Visibility   string        `json:"visibility"`
	AddedAt      sql.NullTime  `json:"added_at"`
}
