// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Competitor struct {
	ID              int32         `json:"id"`
	GroupID         sql.NullInt32 `json:"group_id"`
	Name            string        `json:"name"`
	SocialMediaLink string        `json:"social_media_link"`
	CreatedAt       sql.NullTime  `json:"created_at"`
}

type Group struct {
	ID              int32          `json:"id"`
	UserID          sql.NullInt32  `json:"user_id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	SocialMediaLink string         `json:"social_media_link"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type GroupItem struct {
	ID        int32                 `json:"id"`
	GroupID   sql.NullInt32         `json:"group_id"`
	Type      sql.NullString        `json:"type"`
	Data      pqtype.NullRawMessage `json:"data"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Post struct {
	ID              int32         `json:"id"`
	GroupID         sql.NullInt32 `json:"group_id"`
	Title           string        `json:"title"`
	SocialMediaLink string        `json:"social_media_link"`
	CreatedAt       sql.NullTime  `json:"created_at"`
}

type User struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
